name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: docker://hydrocat/open3d-headless:v0.1

    steps:
    - uses: actions/checkout@v2
    - name: Generate Makefile
      run: cmake -DENABLE_HEADLESS_RENDERING=ON -DBUILD_GUI=OFF -DUSE_SYSTEM_GLEW=OFF -DUSE_SYSTEM_GLFW=OFF ..
      
    - name: Build it
      run: make -j
      
    - name: Make python package
      run: make python-package
      
    - name: tar the release
      run: tar -zcf open3d-headless.tar.gz lib
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Test upload-to-github-release works with ```actions/create-release```
        draft: true
        prerelease: false
    - uses: xresloader/upload-to-github-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "open3d-headless.tar.gz "
        release_id: ${{ steps.create_release.outputs.id }}
        overwrite: true
        verbose: true
    
