name: Compile Open3d Headless

on: workflow_dispatch

# on:
#   schedule:
#     - cron: "30 12 ? * MON"

jobs:

  build_and_make_release:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    container: ubuntu:22.04

    steps:
    - uses: actions/checkout@v2
# Running different steps makes it very hard to run locally.
    - name: Do everything.
      run: |
        # Insall deps
        echo OPEN3D_VERSION="BOUS_VERSION" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v0.1.14
      with:
        files: |
          open3d-headless.tar.gz
        tag_name: ${{env.OPEN3D_VERSION}}
        name: ${{env.OPEN3D_VERSION}}
